version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: task_manager
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
